name: GitHub Actions On Pull Request
run-name: ${{ github.actor }} está ejecutando un pull request
on: 
  pull_request:
    branches:
      - main
jobs:
  Initial-Prints:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: echo "El autor del pull es ${{ github.actor }}."
      - run: echo "El commit ID del último commit es ${{ github.event.pull_request.head.sha }}"
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
